# Generated by Django 5.1.6 on 2025-03-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP Code', 'verbose_name_plural': 'OTP Codes'},
        ),
    ]
